export {
  IMMERSIVE_SHEET_HEADER_BAR as FIELD_EDITOR_HEADER_BAR,
  IMMERSIVE_SHEET_HEADER_ZONE as FIELD_EDITOR_HEADER_ZONE,
  IMMERSIVE_SHEET_HEIGHT as FIELD_EDITOR_SHEET_HEIGHT,
  IMMERSIVE_SHEET_TOP_PEEK as FIELD_EDITOR_SHEET_TOP_PEEK,
} from "@/lib/layout/immersive-sheet";
