import type { InstitutionLogoEntry } from "@/lib/institutions/logo-registry-types";

/** Logo registry for all institutions in {@link INSTITUTION_REGISTRY}. */
export const INSTITUTION_LOGO_REGISTRY: readonly InstitutionLogoEntry[] = [
  {
    institutionId: "cib",
    status: "available",
    logoPath: "/institutions/cib.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "nbe",
    status: "available",
    logoPath: "/institutions/nbe.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "banque_misr",
    status: "available",
    logoPath: "/institutions/banque_misr.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "banque_du_caire",
    status: "available",
    logoPath: "/institutions/banque_du_caire.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "qnb_alahli",
    status: "available",
    logoPath: "/institutions/qnb_alahli.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "hsbc",
    status: "available",
    logoPath: "/institutions/hsbc.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "alexbank",
    status: "available",
    logoPath: "/institutions/alexbank.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "credit_agricole",
    status: "available",
    logoPath: "/institutions/credit_agricole.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "fab",
    status: "available",
    logoPath: "/institutions/fab.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "adcb",
    status: "available",
    logoPath: "/institutions/adcb.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "arab_bank",
    status: "available",
    logoPath: "/institutions/arab_bank.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "nbk",
    status: "available",
    logoPath: "/institutions/nbk.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "al_baraka",
    status: "available",
    logoPath: "/institutions/al_baraka.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "suez_canal",
    status: "available",
    logoPath: "/institutions/suez_canal.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "vodafone_cash",
    status: "available",
    logoPath: "/institutions/vodafone_cash.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "orange_cash",
    status: "available",
    logoPath: "/institutions/orange_cash.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "etisalat_cash",
    status: "available",
    logoPath: "/institutions/etisalat_cash.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "aaib",
    status: "available",
    logoPath: "/institutions/aaib.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "adib",
    status: "available",
    logoPath: "/institutions/adib.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "attijariwafa",
    status: "available",
    logoPath: "/institutions/attijariwafa.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "mashreq",
    status: "available",
    logoPath: "/institutions/mashreq.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "kfh",
    status: "available",
    logoPath: "/institutions/kfh.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "abk",
    status: "available",
    logoPath: "/institutions/abk.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "bank_abc",
    status: "available",
    logoPath: "/institutions/bank_abc.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "faisal_islamic",
    status: "available",
    logoPath: "/institutions/faisal_islamic.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "united_bank",
    status: "available",
    logoPath: "/institutions/united_bank.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "opay",
    status: "available",
    logoPath: "/institutions/opay.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "tabby",
    status: "available",
    logoPath: "/institutions/tabby.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "tamara",
    status: "available",
    logoPath: "/institutions/tamara.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "meeza",
    status: "available",
    logoPath: "/institutions/meeza.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "contact",
    status: "available",
    logoPath: "/institutions/contact.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "aman",
    status: "available",
    logoPath: "/institutions/aman.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "klivvr",
    status: "available",
    logoPath: "/institutions/klivvr.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "paymob",
    status: "available",
    logoPath: "/institutions/paymob.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "money_fellows",
    status: "available",
    logoPath: "/institutions/money_fellows.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "mnt_halan",
    status: "available",
    logoPath: "/institutions/mnt_halan.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "shahry",
    status: "available",
    logoPath: "/institutions/shahry.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "saib",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "egbank",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "emirates_nbd",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "hdb",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "edbe",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "aib",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "abe",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "bank_nxt",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "we_pay",
    status: "available",
    logoPath: "/institutions/we_pay.svg",
    isOfficial: true,
    lastUpdated: "2026-06-19",
  },
  {
    institutionId: "instapay",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "fawry",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "valu",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "telda",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "khazna",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "lucky",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "sympl",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "souhoola",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "thndr",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "bokra",
    status: "fallback",
    logoPath: null,
  },
  {
    institutionId: "mid_bank",
    status: "fallback",
    logoPath: null,
  },
] as const;

export function getInstitutionLogoEntry(
  institutionId: string,
): InstitutionLogoEntry | undefined {
  return INSTITUTION_LOGO_REGISTRY.find((entry) => entry.institutionId === institutionId);
}

export function getInstitutionLogoPath(institutionId: string): string | null {
  const entry = getInstitutionLogoEntry(institutionId);
  return entry?.status === "available" ? entry.logoPath : null;
}
