import type { InstitutionRegistryEntry } from "@/lib/institutions/registry-types";

/** All institutions supported by NUME, grouped by category. */
export const INSTITUTION_REGISTRY: readonly InstitutionRegistryEntry[] = [
  // — Banks —
  {
    id: "cib",
    shortName: "CIB",
    fullName: "Commercial International Bank",
    category: "bank",
    matchValues: ["Commercial International Bank Egypt"],
  },
  {
    id: "nbe",
    shortName: "NBE",
    fullName: "National Bank of Egypt",
    category: "bank",
    matchValues: ["National Bank of Egypt", "البنك الأهلي المصري"],
  },
  {
    id: "banque_misr",
    shortName: "Banque Misr",
    fullName: "Banque Misr",
    category: "bank",
    matchValues: ["بنك مصر", "BM"],
  },
  {
    id: "banque_du_caire",
    shortName: "Banque du Caire",
    fullName: "Banque du Caire",
    category: "bank",
    matchValues: ["BDC"],
  },
  {
    id: "qnb_alahli",
    shortName: "QNB Alahli",
    fullName: "QNB Al Ahli",
    category: "bank",
    matchValues: ["QNB", "Qatar National Bank"],
  },
  {
    id: "hsbc",
    shortName: "HSBC",
    fullName: "HSBC Bank Egypt",
    category: "bank",
    matchValues: ["HSBC Egypt"],
  },
  {
    id: "alexbank",
    shortName: "AlexBank",
    fullName: "Bank of Alexandria",
    category: "bank",
  },
  {
    id: "credit_agricole",
    shortName: "Crédit Agricole",
    fullName: "Crédit Agricole Egypt",
    category: "bank",
    matchValues: ["Credit Agricole"],
  },
  {
    id: "aaib",
    shortName: "AAIB",
    fullName: "Arab African International Bank",
    category: "bank",
    matchValues: ["البنك العربي الأفريقي الدولي"],
  },
  {
    id: "fab",
    shortName: "FAB",
    fullName: "First Abu Dhabi Bank – Misr",
    category: "bank",
    matchValues: ["First Abu Dhabi Bank"],
  },
  {
    id: "adcb",
    shortName: "ADCB",
    fullName: "Abu Dhabi Commercial Bank Egypt",
    category: "bank",
    matchValues: ["Abu Dhabi Commercial Bank"],
  },
  {
    id: "arab_bank",
    shortName: "Arab Bank",
    fullName: "Arab Bank",
    category: "bank",
    matchValues: ["Arab Bank PLC"],
  },
  {
    id: "nbk",
    shortName: "NBK",
    fullName: "National Bank of Kuwait – Egypt",
    category: "bank",
    matchValues: ["National Bank of Kuwait"],
  },
  {
    id: "saib",
    shortName: "SAIB",
    fullName: "Société Arabe Internationale de Banque",
    category: "bank",
  },
  {
    id: "egbank",
    shortName: "EGBANK",
    fullName: "Egyptian Gulf Bank",
    category: "bank",
    matchValues: ["EG Bank"],
  },
  {
    id: "adib",
    shortName: "ADIB",
    fullName: "Abu Dhabi Islamic Bank Egypt",
    category: "bank",
    matchValues: ["Abu Dhabi Islamic Bank"],
  },
  {
    id: "faisal_islamic",
    shortName: "Faisal Islamic Bank",
    fullName: "Faisal Islamic Bank of Egypt",
    category: "bank",
  },
  {
    id: "al_baraka",
    shortName: "Al Baraka Bank",
    fullName: "Al Baraka Bank Egypt",
    category: "bank",
  },
  {
    id: "mid_bank",
    shortName: "MID Bank",
    fullName: "MIDBank",
    category: "bank",
    matchValues: ["MIDBank"],
  },
  {
    id: "emirates_nbd",
    shortName: "Emirates NBD",
    fullName: "Emirates NBD Egypt",
    category: "bank",
  },
  {
    id: "hdb",
    shortName: "HDB",
    fullName: "Housing & Development Bank",
    category: "bank",
    matchValues: ["Housing and Development Bank", "Housing & Development Bank"],
  },
  {
    id: "edbe",
    shortName: "EBank",
    fullName: "Export Development Bank of Egypt",
    category: "bank",
    matchValues: ["Export Development Bank", "Export Development Bank of Egypt"],
  },
  {
    id: "united_bank",
    shortName: "United Bank",
    fullName: "The United Bank",
    category: "bank",
  },
  {
    id: "attijariwafa",
    shortName: "Attijariwafa",
    fullName: "Attijariwafa Bank Egypt",
    category: "bank",
    matchValues: ["Attijariwafa Bank"],
  },
  {
    id: "suez_canal",
    shortName: "Suez Canal Bank",
    fullName: "Suez Canal Bank",
    category: "bank",
    matchValues: ["SCB"],
  },
  {
    id: "kfh",
    shortName: "KFH",
    fullName: "Kuwait Finance House Egypt",
    category: "bank",
    matchValues: ["Ahli United Bank", "Kuwait Finance House"],
  },
  {
    id: "abk",
    shortName: "ABK",
    fullName: "Al Ahli Bank of Kuwait Egypt",
    category: "bank",
    matchValues: ["Al Ahli Bank of Kuwait"],
  },
  {
    id: "mashreq",
    shortName: "Mashreq",
    fullName: "Mashreq Bank",
    category: "bank",
    matchValues: ["Mashreq Bank Egypt"],
  },
  {
    id: "bank_abc",
    shortName: "Bank ABC",
    fullName: "Arab Banking Corporation Egypt",
    category: "bank",
    matchValues: ["Bank ABC", "Arab Banking Corporation"],
  },
  {
    id: "aib",
    shortName: "AIB",
    fullName: "Arab International Bank",
    category: "bank",
  },
  {
    id: "abe",
    shortName: "ABE",
    fullName: "Agricultural Bank of Egypt",
    category: "bank",
    matchValues: ["Agricultural Bank"],
  },
  {
    id: "bank_nxt",
    shortName: "Bank NXT",
    fullName: "Bank NXT",
    category: "bank",
  },

  // — Financial services —
  {
    id: "vodafone_cash",
    shortName: "Vodafone Cash",
    fullName: "Vodafone Cash",
    category: "financial_service",
  },
  {
    id: "orange_cash",
    shortName: "Orange Cash",
    fullName: "Orange Cash",
    category: "financial_service",
  },
  {
    id: "etisalat_cash",
    shortName: "Etisalat Cash",
    fullName: "Etisalat Cash",
    category: "financial_service",
  },
  {
    id: "we_pay",
    shortName: "WE Pay",
    fullName: "WE Pay",
    category: "financial_service",
    matchValues: ["WE Pay Wallet"],
  },
  {
    id: "instapay",
    shortName: "InstaPay",
    fullName: "InstaPay",
    category: "financial_service",
    matchValues: ["Insta Pay"],
  },
  {
    id: "fawry",
    shortName: "Fawry",
    fullName: "Fawry",
    category: "financial_service",
  },
  {
    id: "valu",
    shortName: "valU",
    fullName: "valU",
    category: "financial_service",
    matchValues: ["ValU"],
  },
  {
    id: "aman",
    shortName: "Aman",
    fullName: "Aman",
    category: "financial_service",
  },
  {
    id: "contact",
    shortName: "Contact",
    fullName: "Contact",
    category: "financial_service",
  },
  {
    id: "money_fellows",
    shortName: "Money Fellows",
    fullName: "Money Fellows",
    category: "financial_service",
  },
  {
    id: "telda",
    shortName: "Telda",
    fullName: "Telda",
    category: "financial_service",
  },
  {
    id: "khazna",
    shortName: "Khazna",
    fullName: "Khazna",
    category: "financial_service",
  },
  {
    id: "lucky",
    shortName: "Lucky",
    fullName: "Lucky",
    category: "financial_service",
  },
  {
    id: "sympl",
    shortName: "Sympl",
    fullName: "Sympl",
    category: "financial_service",
  },
  {
    id: "souhoola",
    shortName: "Souhoola",
    fullName: "Souhoola",
    category: "financial_service",
    matchValues: ["Souhoula"],
  },
  {
    id: "paymob",
    shortName: "Paymob",
    fullName: "Paymob",
    category: "financial_service",
  },
  {
    id: "meeza",
    shortName: "Meeza",
    fullName: "Meeza",
    category: "financial_service",
  },
  {
    id: "opay",
    shortName: "OPay",
    fullName: "OPay",
    category: "financial_service",
  },
  {
    id: "shahry",
    shortName: "Shahry",
    fullName: "Shahry",
    category: "financial_service",
  },
  {
    id: "tabby",
    shortName: "Tabby",
    fullName: "Tabby",
    category: "financial_service",
  },
  {
    id: "tamara",
    shortName: "Tamara",
    fullName: "Tamara",
    category: "financial_service",
  },
  // Additional Egyptian fintech (legacy account data)
  {
    id: "thndr",
    shortName: "Thndr",
    fullName: "Thndr",
    category: "financial_service",
  },
  {
    id: "klivvr",
    shortName: "Klivvr",
    fullName: "Klivvr",
    category: "financial_service",
  },
  {
    id: "bokra",
    shortName: "Bokra",
    fullName: "Bokra",
    category: "financial_service",
  },
  {
    id: "mnt_halan",
    shortName: "MNT-Halan",
    fullName: "MNT-Halan",
    category: "financial_service",
    matchValues: ["Halan", "MNT Halan"],
  },
] as const;

export const INSTITUTION_REGISTRY_BANKS = INSTITUTION_REGISTRY.filter(
  (entry) => entry.category === "bank",
);

export const INSTITUTION_REGISTRY_FINANCIAL_SERVICES =
  INSTITUTION_REGISTRY.filter((entry) => entry.category === "financial_service");
